.vscode/extensions.json

Sort recommended VS Code extensions

---

.gitignore
.vscode/extensions.json
tools/diffsharp/functions.fsx
tools/diffsharp/run.fsx
tools/scilean/Main.lean

Another followup to #27 and #28.

Autoformat F# and Lean too

---

tools/diffsharp/Dockerfile
tools/diffsharp/gradbench.fsx
tools/diffsharp/modules.fsx
tools/diffsharp/run.fsx

Adding a function to wrap JSON input and output around function.

Wrap Function for DiffSharp

---

README.md
logo.svg

This PR adds a logo that I drew with [Radish](https://radish.is/drawing):
```tsx
const vec2 = (x, y) => [x, y];
const str = (points) =>
points.map(([x, y]) => `${x},${y}`).join(" ");
const size = 500;
const gap = 50;
const thickness = 50;
const height = size / 2 - (gap + gap / 2);
const width = height / (Math.sqrt(3) / 2);
const grad = () => {
return [
vec2(size / 2 + width / 2, gap),
vec2(size / 2 - width / 2, gap),
vec2(size / 2, size / 2 - gap / 2),
];
};
const bench = () => {
return [
vec2(size - gap, size - gap),
vec2(size - gap, size / 2 + gap / 2),
vec2(gap, size / 2 + gap / 2),
vec2(gap, size - gap),
vec2(gap + thickness, size - gap),
vec2(gap + thickness, size / 2 + gap / 2 + thickness),
vec2(size - (gap + thickness), size / 2 + gap / 2 + thickness),
vec2(size - (gap + …
```

Add a logo

---

package-lock.json
packages/gradbench/src/App.css
packages/gradbench/src/App.tsx

Updating the [website](https://gradbench.org) to include relevant information and links.

Updating the Website

---

evals/gmm/Dockerfile
evals/gmm/data_gen.py
evals/gmm/main.py
shared/ADBench/ba_data.py
shared/ADBench/ba_sparse_mat.py
tools/pytorch/run.py

Removed extra imports that are no longer needed and adding in ADBench links

Cleaning GMM and Shared

---

packages/gradbench/src/App.tsx

Updated website to include BA inclusion and more clear link to ADBench

Website Updates

---

crates/adroit/src/typecheck/mod.rs

#61 made `Module::gc` get rid of any sharing in `vals` by removing hashing, for the performance benefit. I suspect that this could violate an assumption we make in the process:
https://github.com/gradbench/gradbench/blob/8e439743141e6cbb235f277be7b8c6ffd9f355e8/crates/adroit/src/typecheck/mod.rs#L491
So, this PR adds back the sharing to reduce the size of `vals`, not by using hashing, but instead by taking advantage of the fact that `Def`s and `Param`s must always point to themselves, and we've already processed those before we get to the `Expr`s, so then if we see a `Src::Def` or a `Src::Param` we can just return early.
I was hoping this would also increase performance a bit and push us past the 500k lines of code per second mark, but sadly it did not.

Re-deduplicate `Val`s

---

README.md

This PR adds a couple nice badges to our README.

Add badges in `README.md`

---

.vscode/extensions.json

Switch to new Adroit VS Code extension

---

docker/mathlib4/Dockerfile
evals/ba/Dockerfile
evals/gmm/Dockerfile
evals/hello/Dockerfile
tools/autograd/Dockerfile
tools/diffsharp/Dockerfile
tools/jax/Dockerfile
tools/mygrad/Dockerfile
tools/pytorch/Dockerfile
tools/scilean/Dockerfile
tools/tapenade/Dockerfile
tools/tensorflow/Dockerfile
tools/zygote/Dockerfile

Updated GMM Dockerfile to install `python:3.12-slim` to be compatible with NumPy 1.26

Fix GMM Build

---

python/gradbench/tensorflow/gmm.py
python/gradbench/tensorflow/gmm_objective.py
python/gradbench/tensorflow/utils.py
tools/tensorflow/Dockerfile

Implements [GMM](https://github.com/microsoft/ADBench/blob/master/src/python/modules/Tensorflow/TensorflowGMM.py) for TensorFlow

GMM for TensorFlow

---

.github/workflows/build.yml
.github/workflows/nightly.yml

Noticed that CI was passing for #101 when it shouldn't have been.

Use `set -o pipefail` before piping to `tee`

---

.github/workflows/nightly.yml

Run `docker save` in nightly before upload

---

.github/workflows/nightly.yml

More stuff I overlooked in #111.

Fix nightly download dir and other stuff

---

.github/summarize.py
.github/workflows/nightly.yml
.gitignore

Following up on #118, this PR tries pushing to a branch instead of creating a release.

Push nightly run results to a branch

---

.github/workflows/nightly.yml

Following up on #119 to make it easier to download by date.

Create a nightly tag

---

.github/summarize.py
.github/workflows/nightly.yml

Put date in the nightly summary JSON

---

README.md

It's more relevant since that's the data the website pulls from anyway.

Replace README `main` status badge with nightly

---

python/gradbench/evals/gmm/run.py
python/gradbench/evaluation.py

Not sure how that snuck through.

Fix workload labels.

---

.vscode/extensions.json

Recommend rust-analyzer for VS Code

---

python/gradbench/pytorch/gmm_objective.py

This makes PyTorch perform far better.
Work by Ola Rønning.

gmm_objective.py: vectorize operations.

---

tools/enzyme/README.md

Missed this while reviewing #148.

Fix header in Enzyme README

---

tools/adol-c/.gitignore
tools/adol-c/AdolCBA.cpp
tools/adol-c/AdolCBA.h
tools/adol-c/AdolCGMM.cpp
tools/adol-c/AdolCGMM.h
tools/adol-c/AdolCHT.cpp
tools/adol-c/AdolCHT.h
tools/adol-c/AdolCHello.cpp
tools/adol-c/AdolCHello.h
tools/adol-c/Dockerfile
tools/adol-c/Makefile
tools/adol-c/README.md
tools/adol-c/ba.py
tools/adol-c/gmm.py
tools/adol-c/hello.py
tools/adol-c/ht.py
tools/adol-c/run.py
tools/adol-c/run_ba.cpp
tools/adol-c/run_gmm.cpp
tools/adol-c/run_hello.cpp
tools/adol-c/run_ht.cpp

Will eventually port ADBench implementations, but hello is implemented from scratch.
ADOL-C has a very weird API.

Add ADOL-C tool.

---

tools/enzyme/.gitignore
tools/enzyme/EnzymeGMM.cpp
tools/enzyme/EnzymeGMM.h
tools/enzyme/Makefile
tools/enzyme/gmm.py
tools/enzyme/run_gmm.cpp

I figured out why my first attempt didn't work. Instead of reading the rather austere documentation, I thought about how it *should* work (somehow passing in a nonzero seed vector for the cotangents) and looked for a way to do something that looks like that.

Implement gmm with Enzyme.

---

tools/enzyme/EnzymeGMM.cpp

It may be a good idea to use --runs 2 in CI to ensure these errors don't occur.

Make Enzyme-GMM work with multiple runs.

---

cpp/adbench/shared/matrix.h
tools/cppad/.gitignore
tools/cppad/CppADGMM.cpp
tools/cppad/CppADGMM.h
tools/cppad/CppADHello.cpp
tools/cppad/CppADHello.h
tools/cppad/CppADLSTM.cpp
tools/cppad/CppADLSTM.h
tools/cppad/Dockerfile
tools/cppad/Makefile
tools/cppad/README.md
tools/cppad/gmm.py
tools/cppad/hello.py
tools/cppad/lstm.py
tools/cppad/run.py
tools/cppad/run_gmm.cpp
tools/cppad/run_hello.cpp
tools/cppad/run_lstm.cpp

Implement LSTM, GMM, and Hello with CppAD.

---

CONTRIBUTING.md
crates/gradbench/src/cli.rs

Add commands to both build and run Docker images

---

CONTRIBUTING.md
evals/lstm/README.md
python/gradbench/gradbench/eval.py
python/gradbench/gradbench/evals/ba/run.py
python/gradbench/gradbench/evals/gmm/run.py
python/gradbench/gradbench/evals/hello/run.py
python/gradbench/gradbench/evals/ht/run.py
python/gradbench/gradbench/evals/lstm/run.py

Following up on https://github.com/gradbench/gradbench/pull/200#issuecomment-2622660139.

Consistently say "eval" instead of "evaluation"

---

python/gradbench/gradbench/comparison.py
python/gradbench/gradbench/eval.py

Accept comparisons of floats and ints.

---

.github/workflows/build.yml
Cargo.lock
crates/gradbench/Cargo.toml
crates/gradbench/src/main.rs
crates/gradbench/src/outputs/readme_example.txt

Unit-test the CLI

---

python/gradbench/gradbench/eval.py
python/gradbench/gradbench/evals/ba/run.py
python/gradbench/gradbench/evals/gmm/run.py
python/gradbench/gradbench/evals/ht/run.py
python/gradbench/gradbench/evals/lstm/run.py

For simplicity, disabled validation is transmitted as valid at the protocol level. A future extension could make it explicit that the result is not validated.

Make it possible to disable validation.

---

tools/tapenade/Dockerfile

Use new base for Tapenade Dockerfile

---

nix/adept.nix
nix/cppad.nix

Forgot these when I moved shell.nix from the scripts branch.

Add missing .nix files

---

evals/kmeans/README.md

Followup on #194 since I didn't see any square roots in the existing implementations; @athas is this correct?

Document squared distance in k-means

---

python/gradbench/gradbench/evals/kmeans/run.py

Make kmeans data generation deterministic.

---

tools/haskell/README.md

Fix link in Haskell tool README

---

.vscode/extensions.json

This PR adds the following additional VS Code extensions to our `"recommendations"` in `.vscode/extensions.json`:
- [Futhark](https://marketplace.visualstudio.com/items?itemName=DIKU.futhark-vscode)
- [GitHub Actions](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-github-actions)
- [Docker](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-docker)
- [Bun for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=oven.bun-vscode)
- [Even Better TOML](https://marketplace.visualstudio.com/items?itemName=tamasfe.even-better-toml)

Recommend more VS Code extensions

---

python/gradbench/gradbench/evals/gmm/run.py

This makes the runtime graph smoother.

Sort GMM workloads roughly in increasing size

---

tools/adept/Dockerfile

curl'ing random files from Savannah is not terribly sound engineering, it turns out. cp'ing random files from the local Debian, however...

adept: make Dockerfile more robust

---

tools/adol-c/evals.txt
tools/adol-c/kmeans.py
tools/adol-c/run_kmeans.cpp

Strangely slow, despite using API functions that seem like they should do the efficient thing.

Implement kmeans with adol-c

---

python/gradbench/gradbench/tools/tensorflow/ba.py
python/gradbench/gradbench/tools/tensorflow/gmm.py

They are now based on the "graph" versions from ADBench, which is often orders of magnitudes faster than the "eager" versions.
I will probably also port the others eventually.

Make TensorFlow implementations much faster.

---

python/gradbench/gradbench/tools/jax/run.py
python/gradbench/gradbench/tools/pytorch/run.py
python/gradbench/gradbench/tools/tensorflow/run.py

Otherwise it is very annoying to debug errors that occur during the import.

tensorflow, pytorch, jax run.py: show error on import failure

---

python/gradbench/gradbench/tools/tensorflow/ht.py
python/gradbench/gradbench/tools/tensorflow/ht_objective.py
python/gradbench/gradbench/tools/tensorflow/lstm.py
python/gradbench/gradbench/tools/tensorflow/lstm_objective.py
tools/tensorflow/Dockerfile
tools/tensorflow/evals.txt

These are ported from ADBench.

Implement lstm and ht with TensorFlow

---

.github/workflows/build.yml
.github/workflows/nightly.yml
crates/gradbench/src/main.rs

Meant to enable #224 to be merged.

Allow x86-only tools in CI

---

crates/gradbench/src/stats.rs

This way we can link to it from the new README in #341.

Generate an SVG of the summary table

---

tools/futhark/Dockerfile

futhark: upgrade to 0.25.28

---

python/gradbench/gradbench/evals/gmm/run.py
tools/cppad/evals.txt

This is still not quite all of them, as the even larger ones probably use too much memory for CI.

gmm: enable more workloads

---

cpp/gradbench/main.hpp

This is a monotonic clock, so it fixes #372.

Use steady_clock for C++

---

tools/enzyme/Dockerfile

This greatly improves iteration speed.

`COPY` Python only after Enzyme build in Docker

---

README.md

I think we can make this claim now that #378 and #397 are merged?

Strengthen related work comparison claim in README

---

crates/gradbench/src/stats.rs

Plotting will take more work, but this at least makes the grid look better.

Compute stats for particle and saddle

---

CONTRIBUTING.md

This adds some more things that I think are useful. (Note that some of it is a declaration of policy that I am not-so-sneakily trying to smuggle in.)

CONTRIBUTING.md: add more information

---

shell.nix
tools/zygote/README.md

Also adds julia to shell.nix, because why not.

zygote: document how to run outside of Docker

---

shell.nix

shell.nix: only include Julia on x86_64-linux

---

julia/GradBench/src/GradBench.jl
julia/GradBench/src/benchmarks/det.jl
tools/enzyme-jl/evals.txt
tools/enzyme-jl/run.jl
tools/enzyme-jl/run_det.jl
tools/zygote/evals.txt
tools/zygote/run.jl
tools/zygote/run_det.jl

I am uncertain if the enzyme-jl implementation will use too much memory to run in CI, but let's see.

det: implement with zygote and enzyme-jl

---

julia/GradBench/src/benchmarks/gmm.jl
tools/zygote/evals.txt
tools/zygote/run_ba.jl
tools/zygote/run_gmm.jl

This is now more similar to ADBench. I also added an explanatory comment for why I think it is written this way.

Speed up gmm-zygote and ba-zygote

---

julia/GradBench/src/GradBench.jl
julia/GradBench/src/benchmarks/llsq.jl
tools/enzyme-jl/evals.txt
tools/enzyme-jl/run.jl
tools/enzyme-jl/run_llsq.jl
tools/zygote/evals.txt
tools/zygote/run.jl
tools/zygote/run_llsq.jl

The Enzyme.jl performance is quite good, and the Zygote performance is less good.
Closes #505.
Closes #449.

llsq: implement with zygote and enzyme-jl

---

tools/enzyme-jl/evals.txt
tools/enzyme-jl/run.jl
tools/enzyme-jl/run_lstm.jl

This one is not very nice, as it requires `Enzyme.API.strictAliasing!(false)`.

enzyme-jl: implement lstm

---

cpp/gradbench/evals/det.hpp
tools/codipack/Makefile
tools/codipack/README.md
tools/codipack/ba.cpp
tools/codipack/codi_impl.hpp
tools/codipack/det.cpp
tools/codipack/gmm.cpp
tools/codipack/hello.cpp
tools/codipack/ht.cpp
tools/codipack/kmeans.cpp
tools/codipack/llsq.cpp
tools/codipack/lse.cpp
tools/codipack/lstm.cpp
tools/codipack/ode.cpp

Improvements for the CoDiPack implementation.
This shows the time changes for the improvements:
[analysis_improvement.pdf](https://github.com/user-attachments/files/19862425/analysis_improvement.pdf)
This shows the timing for the different CoDiPack types. In general the test cases are to small for the other types. But have to have a closer look.
[analysis_versions.pdf](https://github.com/user-attachments/files/19862426/analysis_versions.pdf)

codipack improvement

---

tools/ad-hpp/.gitignore
tools/ad-hpp/Makefile
tools/ad-hpp/evals.txt
tools/ad-hpp/kmeans.cpp
tools/ad-hpp/particle.cpp

work in progress, I am open to suggestions.

ad.hpp: kmeans, particle

---

CITATION.cff

I overlooked him the first time around.

CITATION.cff: add Valentin

---

.github/workflows/build.yml
CONTRIBUTING.md
Cargo.lock
crates/gradbench/Cargo.toml
crates/gradbench/src/lint.rs
crates/gradbench/src/main.rs
js/website/package.json
package.json

Resolves #554 and hopefully also resolves #576.

Add a `repo lint` CLI subcommand

---

.github/workflows/build.yml
crates/gradbench/src/lint.rs
crates/gradbench/src/main.rs
nix/sources.nix
shell.nix

Add nixfmt as a linter
