CONTRIBUTING.md
Following up on #5, this PR changes the containerd link in `CONTRIBUTING.md` to point to [the page for Docker Engine](https://docs.docker.com/storage/containerd/) instead of [the page for Docker Desktop](https://docs.docker.com/desktop/containerd/), because the former points to the latter but not vice versa.
=> Link to CLI doc page for containerd

CONTRIBUTING.md
This PR follows up on #5 by adding extra instructions necessary for running building multi-platform Docker images in headless Linux.
=> Add `CONTRIBUTING.md` instructions to install QEMU

docker/mathlib4/Dockerfile, tools/jax/Dockerfile, tools/mygrad/Dockerfile, tools/pytorch/Dockerfile, tools/scilean/Dockerfile, tools/tapenade/Dockerfile, tools/tensorflow/Dockerfile, tools/zygote/Dockerfile
This PR adds a [`LABEL org.opencontainers.image.source`](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#labelling-container-images) line to each of our `Dockerfile`s, allowing GitHub to automatically detect that the resulting Docker images come from this repo. I believe that this should mean that the resulting GHCR packages should [automatically give access](https://docs.github.com/en/packages/learn-github-packages/about-permissions-for-github-packages#permissions-for-repository-scoped-packages) to @gradbench/team, which has maintain access to this repository.
=> Label every Docker image with this repository URL

tools/scilean/Main.lean, tools/scilean/lakefile.lean
You can now run `benchAD` function but calling `runBenchAD` in `main` function.
=> SciLean update: run AD benchmark in IO

.github/workflows/build.yml, CONTRIBUTING.md, eval.sh, run.py, tool.sh
The `run.py` script added in #25 only supports running the GradBench Docker images. This PR changes it so it can take in arbitrary commands, using [`shlex.split`](https://docs.python.org/3/library/shlex.html#shlex.split) to split them:
```sh
./run.py --eval './eval.sh hello' --tool tools/scilean/.lake/build/bin/gradbench
```
=> Allow non-Docker commands in `run.py`

.github/workflows/build.yml
This PR fixes a mistake from #32.
=> Fix typo in `run` CI job

.github/actions/space/action.yml, .github/matrix.py, .github/workflows/build.yml, .github/workflows/nightly.yml
This PR adds a new "Nightly" workflow in GitHub Actions that builds all our Docker images every day at 1am UTC (9pm Eastern). It's a bit difficult to test CI/CD stuff like this without merging, so I'm gonna merge this and test it via [`workflow_dispatch`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch).
=> Build nightly Docker images

.github/workflows/nightly.yml, manual.sh
Following up on #38, this PR makes our nightly builds use the [`--all-tags`](https://docs.docker.com/reference/cli/docker/image/push/#all-tags) option so that they push to the `latest` tag instead of just the tag for the current date. That will allow users to automatically build the Docker images via our `run.py` script.
=> Mark the nightly images as `latest`

README.md
Following up on #39, this PR adds instructions in `README.md` for people to run our nightly Docker images without building them.
In future, we should make it possible to run GradBench without cloning this repo at all.
=> Give nightly usage in the `README`

CONTRIBUTING.md
#14 added a section in `CONTRIBUTING.md` describing how to install all our dependencies from [npm](https://npmjs.com/) to build the VS Code image; this PR extends that section to describe how to locally develop the https://gradbench.org/ website too.
=> Describe the website in `CONTRIBUTING.md`

tools/autograd/Dockerfile, tools/autograd/gradbench.py, tools/autograd/run.py, tools/jax/Dockerfile, tools/jax/gradbench.py, tools/jax/run.py, tools/mygrad/Dockerfile, tools/mygrad/gradbench.py, tools/mygrad/run.py, tools/tapenade/run.py, tools/tensorflow/Dockerfile, tools/tensorflow/gradbench.py, tools/tensorflow/run.py
Updating Autograd, Jax, MyGrad, and TensorFlow with the wrapper function originally written for PyTorch. This wrapper is a [decorator](https://stackoverflow.com/questions/739654/how-do-i-make-function-decorators-and-chain-them-together) that has similar functionality to those for SciLean and DiffSharp.
Autograd inputs and outputs do not really require adjustment. Currently I have a lambda function multiplying by 1.0 to ensure floats. This is not strictly necessary.
Tapenade is written in a combination of Python and C but inputs don't need to be changed. Inputs are simply converted to strings (and multiplied by 1.0 to ensure they are floats) when sent to C files and converted back to floats to be returned in JSON. A wrapper could be implemented here but it is not needed.
Similarly Zygote …
=> Adding Wrapper to Python Tools

Cargo.lock, crates/adroit/Cargo.toml, crates/adroit/src/lex.rs, crates/adroit/src/parse.rs, crates/adroit/src/typecheck.rs, crates/adroit/src/util.rs
Currently we do `impl From<T> for usize` on every index type, call that via `usize::from`, and use `try_into()` along with direct construction syntax to convert from `usize` to an index type. This PR replaces all that with [`disjoint_sets::ElementType`](https://docs.rs/disjoint-sets/0.4.2/disjoint_sets/trait.ElementType.html), since we're about to start using the disjoint-sets crate anyway for type inference. Specifically, we need a Rust implementation of [union-find](https://en.wikipedia.org/wiki/Disjoint-set_data_structure) so we can do [unification](https://en.wikipedia.org/wiki/Unification_(computer_science)), and disjoint-sets is the best I could find out of the several existing crates:
- [aph_disjoint_set](https://crates.io/crates/aph_disjoint_set)
- 0 GitLab stars
- lots of …
=> Use `disjoint_sets::ElementType` for index types

packages/gradbench/src/App.tsx
Unfortunately #58 made the typechecker slower, so this PR accordingly updates the claim we originally made in #47.
=> Update Adroit performance claim on website

crates/adroit/src/typecheck/mod.rs, packages/gradbench/src/App.tsx
This PR follows up on #58 and #60 by using [`cargo-flamegraph`](https://github.com/flamegraph-rs/flamegraph) to see an `IndexSet<Val>` that should just be a `Vec<Val>`.
=> Speed up typechecker by doing less hashing

crates/adroit/src/main.rs
Previously e.g. in #60 and #61 I would manually insert some code into `crates/adroit/src/compile.rs` to measure and print timing data, then manually gather the data and plug all the numbers into a calculator. This PR gets rid of the need for all that by adding an `adroit perf` subcommand that you can use like this:
```sh
cargo run --release perf -n100000 evals/gmm/gmm.adroit
```
```
100000 × lex       =  0.869 seconds
100000 × parse     =  2.675 seconds
100000 × typecheck = 25.281 seconds
100000 × total     = 28.825 seconds
evals/gmm/gmm.adroit is 139 lines
lines of code per second: 482218
```
=> Add `perf` subcommand to benchmark Adroit compiler

crates/adroit/src/compile.rs
Following up on #66, this PR uses `Printer::new` outside tests so that no dead code warnings show up when we do stuff like [this](https://github.com/johnthagen/min-sized-rust/tree/094d314f0c28f7e4bffeb0b0258f71cb303bd91a?tab=readme-ov-file#remove-panic-string-formatting-with-panic_immediate_abort):
```sh
cargo +nightly build -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort --target wasm32-unknown-unknown --release
```
=> Use `Printer::new` outside `#[cfg(test)]`

.github/workflows/build.yml, Cargo.lock, crates/adroit/Cargo.toml, crates/adroit/src/lex.rs, package-lock.json, packages/vscode/package.json
Followup on #69: the Windows VS Code extension built in GitHub Actions just gives `_` on hover but otherwise seems to work correctly; in contrast, when I build locally, everything works perfectly. This PR fixes the issue by cross-compiling from Linux. It also modifies the lexer so it can recognize Windows-style line endings.
=> Fix Adroit for Windows

Cargo.lock, crates/adroit/Cargo.toml, crates/adroit/src/graph.rs, crates/adroit/src/lsp.rs, package-lock.json, packages/vscode/package.json, packages/vscode/src/extension.ts
This PR expands on #69 by
- tweaking the behavior for identifying relative `import`s
- removing the redundant call to `fetch` for `textDocument/didOpen`
- adding an `adroit.exe` configuration option (mostly useful for local development)
- removing the `file:` restriction so now e.g. `untitled:` works too
=> Make the VS Code extension more flexible

Cargo.lock, crates/adroit/Cargo.toml, crates/adroit/src/pprint/mod.rs, crates/adroit/src/typecheck/mod.rs
See calder/rust-goldenfile#10.
=> Obviate custom `goldenfile` differ

crates/adroit/Cargo.toml, crates/adroit/src/cli.rs, crates/adroit/src/graph.rs
#69 changed the `adroit json` command to only print the typed IR for a single module, in contrast to its previous behavior which printed the entire module graph. This PR changes it back, but now uses URIs instead of indices into a flat topologically-sorted list.
=> Serialize the entire Adroit module graph again

.github/workflows/build.yml, .github/workflows/close-pr.yml
Our main build workflow spawns quite a few jobs, some of which are long-running. The free version of GitHub Actions has a [limit](https://docs.github.com/en/actions/administering-github-actions/usage-limits-billing-and-administration#usage-limits) of 20 concurrent jobs, so this can cause jobs to have to wait a while if, e.g., we push several commits to a pull request within the space of a couple hours. This PR uses the [`concurrency`](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/control-the-concurrency-of-workflows-and-jobs) feature to automatically cancel running CI workflows on further pushes to a PR, and also adds a new "Close PR" workflow which uses the same concurrency group, effectively cancelling any CI workflow runs when the PR gets closed.
=> Cancel existing CI runs on PR push

.github/workflows/build.yml
Followup on #82 to fix [this error](https://github.com/gradbench/gradbench/actions/runs/11021882294):
> **Invalid workflow file:** .github/workflows/build.yml#L9
> `The workflow is not valid. .github/workflows/build.yml (Line: 9, Col: 10): Unexpected value ''`
=> Fix `concurrency` usage for `push` events

.github/matrix.py, .github/workflows/build.yml
This PR splits our `tool` and `run` CI jobs into `tool-fast`/`tool-slow` and `run-fast`/`run-slow` pairs, so that don't have to wait multiple hours for the slow tools to finish building before getting any data from running the evals on the fast tools.
=> Run slow tools separately from fast ones

.github/workflows/build.yml
Followup on #83 which accidentally forced all CI on `main` to run serialized. This PR lets it run in parallel again.
=> Run CI on `main` in parallel again

tools/tapenade/hello.py, tools/tapenade/run.py
Ensures Tapenade only compiles once during the `define` message and then runs that compiled code for `evaluate` calls.
=> Tapenade Compilation Fix

.github/workflows/build.yml, .github/workflows/nightly.yml, .gitignore
This PR adds to our Nightly GitHub Actions workflow a `run` job that uses [`actions/upload-artifact`](https://github.com/actions/upload-artifact) to save the JSON log, then also modifies the `run-fast` and `run-slow` jobs in our Build workflow to save their logs as well.
As a followup, we should add a job to collect all these artifacts and commit and push them to a branch, since GitHub Actions artifacts are ephemeral.
=> Save Build and Nightly results as artifacts

.github/workflows/build.yml, CONTRIBUTING.md, README.md, package-lock.json, package.json
This PR uses [markdown-toc](https://www.npmjs.com/package/markdown-toc) to generate tables of contents for `README.md` and `CONTRIBUTING.md`, and adds a CI check to keep those up to date.
I also removed hard wrapping in the Markdown source.
=> Generate Markdown ToCs

.github/matrix.py
On 2024-09-24 in #81 we created a "slow" list of tools that take a long time to build. For example, on 2024-09-25 in [Nightly build #76](https://github.com/gradbench/gradbench/actions/runs/11044363484/job/30680182588) it took over half an hour. However, the next day on 2024-09-26 in [Nightly build #77](https://github.com/gradbench/gradbench/actions/runs/11063377546/job/30739410907) it only took about seven minutes, and this has continued to be the case ever since. So, this PR removes TensorFlow from the "slow" list.
=> Remove TensorFlow from the "slow" list

.github/matrix.py, .github/workflows/build.yml, .github/workflows/nightly.yml
As a first step for #98, this PR adds a `gold` job to our Build and Nightly workflows, which runs a single tool on all the evals first before running any of the other tools, so that tool's results will be available to validate all the others' against it. In `.github/matrix.py` we specify that our particular choice for this "gold" tool is PyTorch; quoting @athas [on Discord](https://discord.com/channels/1242864568850579487/1267596255886970952/1298393783033139402):
> I would probably use PyTorch as the golden implementations, because it's so popular, so there's a pretty good chance people will be familiar with it. Could also be autograd.
Note that currently, this CI setup runs PyTorch _twice_ on every eval, since it's also a part of the "tool" and "fast" sets that get run after the "gold" …
=> Choose PyTorch as a "gold" tool to run first

.github/workflows/nightly.yml
The [Nightly](https://github.com/gradbench/gradbench/actions/workflows/nightly.yml) CI has been failing since #92 was merged. This PR attempts to fix that.
=> Upload eval and tool artifacts in nightly builds

.github/workflows/build.yml, CONTRIBUTING.md, poetry.lock, pyproject.toml, python/gradbench/futhark/ba.py, python/gradbench/futhark/gmm.py, python/gradbench/futhark/hello.py, python/gradbench/futhark/run.py
#27 added VS Code configuration for autoformatting Python code, but it hasn't been checked in CI. This PR adds those tools to our Poetry config, and renames the `toc` job to a more general `lint` job that runs those tools.
=> Autoformat Python code in CI

.github/release.py, .github/workflows/nightly.yml, .gitignore
For #97, while we could possibly just have the website look up the workflow run for a nightly release and download the artifacts, that introduces a lot of steps and also [the artifacts expire eventually](https://docs.github.com/en/organizations/managing-organization-settings/configuring-the-retention-period-for-github-actions-artifacts-and-logs-in-your-organization). This PR puts the data in an easier place by having the nightly workflow create a GitHub release with all the JSON logs. It also runs a new `.github/release.py` script that collects a summary of all the runs into a single much smaller file, which the website will be able to download to create a table of all evals and tools on the homepage. In the future we could also expand this to add summary files for the rows and columns in …
=> Create nightly release with benchmark data/summary

.github/workflows/nightly.yml
Log from [nightly failures](https://github.com/gradbench/gradbench/actions/runs/11656984084/job/32486384749) since #108:
> ```
> gh: To use GitHub CLI in a GitHub Actions workflow, set the GH_TOKEN environment variable. Example:
>   env:
>     GH_TOKEN: ${{ github.token }}
> ```
And [the docs](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/using-github-cli-in-workflows) say to set `GH_TOKEN` instead of `GITHUB_TOKEN` so I'm doing that here.
=> Set `GH_TOKEN` when using `gh` in nightly workflow

python/gradbench/evals/ba/run.py, python/gradbench/evals/gmm/run.py, python/gradbench/evals/hello/run.py, python/gradbench/evaluation.py
Followup on #101, replacing the boolean-only `correctness(check)` pattern with a richer `assertion(check)` pattern that captures the error message as a string. Hopefully this will help with cases like #103 where the checker itself throws an error due to structure issues before it even begins evaluating its check.
=> Capture validation error messages

.github/workflows/nightly.yml
The [most recent nightly](https://github.com/gradbench/gradbench/actions/runs/11715372548/job/32669554843) failed with this error message:
> HTTP 403: Resource not accessible by integration (https://api.github.com/repos/gradbench/gradbench/releases)
According to [the GitHub docs](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token) for the `contents` permission:
> Work with the contents of the repository. For example, `contents: read` permits an action to list the commits, and `contents: write` allows the action to create a release. For more information, see "[Permissions required for GitHub Apps](https://docs.github.com/en/rest/overview/permissions-required-for-github-apps?apiVersion=2022-11-28#repository-permissio …
=> Give nightly workflow permissions to create a release

.github/errors.py, .github/workflows/build.yml, .github/workflows/nightly.yml
#113 made it possible to capture all kinds of errors from validation, but also made it so that CI no longer fails when a validation error occurs. This PR adds a `.github/errors.py` script that prints any validation errors from a log, and also yields a nonzero exit code if there were any errors.
This script only gets run in the Build workflow, because there, the `run-*` jobs are terminal. It does not run in the Nightly workflow, which feeds the logs into a final `release` job that is meant to produce a bundle of assets that can then be displayed on the website.
=> Check for and print validation errors in CI

run.py
This is useful when piping the result of run.py into 'tee' (or other tools), as Python switches stdout from line to block buffering when stdout is not a tty.
=> Flush stdout after processing a message.

.github/workflows/nightly.yml
Followup on #114 because [the nightly is failing earlier now](https://github.com/gradbench/gradbench/actions/runs/11734858253), this time with the message
> ```
> unexpected status from POST request to https://ghcr.io/v2/gradbench/.../blobs/uploads/: 403 Forbidden
> ```
which I'm guessing is because previously there was implicit permissions and I accidentally disabled those by adding `contents: write`. But it's GitHub Actions, who even knows really. Time to wait and see when the next nightly runs in fifteen minutes.
=> Give nightly workflow package permissions again

.github/workflows/nightly.yml
After the most recent nightly finished, I tried to download the data in #109, but it failed due to CORS.
=> Delete `release` job from Nightly workflow

eval.sh, python/gradbench/evals/ba/run.py, python/gradbench/evals/gmm/run.py, python/gradbench/evals/ht/run.py, tool.sh
Also augments the ba/gmm/ht evals to accept command line options indicating which workloads to run. This is probably the most useful usage of command line options.
By default, when no options are provided, the current selection of workloads is preserved.
=> Allow command line options to be passed to tools and evals.

python/gradbench/evaluation.py, run.py
This message is sent by the eval after it receives a response to an evaluation message, and contains validation information. The idea is that this is used by the run.py script (or equivalent). The eval does not expect a response to the analysis message. The ID of the analysis message is the same as the ID of the evaluation message.
This PR does not change the contents of the "end" message, so validation information is now reported twice (but still only computed once, so there is little risk of inconsistency).
=> Extend protocol with an "analysis" message kind.

python/gradbench/evals/ba/run.py, python/gradbench/evals/gmm/run.py, python/gradbench/evals/hello/run.py, python/gradbench/evals/ht/run.py, python/gradbench/evaluation.py
This extends the eval protocol such that "evaluate" messages must now also have a "workload" field. This field must contain a human-readable string. It is intended for use by analysis tools and carries no semantic meaning. It is intended that every distinct "input" also has a distinct "workload" label.
=> Add workload labels.

.vscode/settings.json, CONTRIBUTING.md, README.md, evals/hello/README.md, python/gradbench/evaluation.py, tools/autograd/README.md, tools/diffsharp/README.md, tools/futhark/README.md, tools/jax/README.md, tools/mygrad/README.md, tools/pytorch/README.md, tools/scilean/README.md, tools/tapenade/README.md, tools/tensorflow/README.md, tools/zygote/README.md
Resolves #95 and then some. The only actual code change here is in the log output for validation: previously the `"analysis"` messages said `"valid"` which was inconsistent with the `"end"` messages that said `"correct"`, so I made them consistent with each other (in this case I just chose the one that we were already using in the `.github/summarize.py` script). I also made it so that, if no `"error"` is provided, it's omitted from the JSON instead of being serialized as `null`.
I disabled Markdown autoformatting because Prettier was introducing too many linebreaks in the JSON examples in `README.md`.
=> Write more documentation

evals/hello/Dockerfile, python/gradbench/evals/gmm/run.py, python/gradbench/evals/hello/run.py
The tolerances here are somewhat arbitrarily set to allow validation with an implementation based on finite differencing. There is room to bikeshed them, but I suggest not doing so, for the following reasons:
0) Even with the very generous gmm tolerance, it is unlikely that a
buggy implementation will have a validating Jacobian.
1) Although a loose tolerance allows implementations to play
mixed-precision games for performance, Gradbench is not a
competition, and so we can assume "good faith" on behalf of the
tools.
Options for configuring the tolerance can always be added later.
=> Increase tolerance when validating gmm and hello.

.github/workflows/build.yml, .github/workflows/close-pr.yml, .github/workflows/nightly.yml
Especially since #104, the high-level view of a GitHub Actions job log in this repo has become hard to read:
To fix the issue, this PR adds a `name` to all the `steps` of every one of our GitHub Actions jobs:
=> Give every GitHub Actions step a `name`

crates/gradbench/src/cli.rs
Followup on #148 because building the Enzyme tool takes over half an hour; cf. #94.
Marking this for review instead of just merging it, because I'm not entirely convinced that this is the right thing to do: the downside is that we would then have to also wait for the two-hour SciLean build to finish before we can get Enzyme results.
One other possibility would be to split into more than two matrix jobs, to account for these different "tiers" of slowness. At that point, though, I would no longer consider it wise to maintain `.github/workflows/build.yml` by hand, so we'd want to autogenerate it. That would add more complexity to the repository, so I'm hesitant to go down that road, having previously worked on a similar CI system in the [PyTorch …
=> Move Enzyme to the "slow" list

python/gradbench/comparison.py, python/gradbench/evals/ba/run.py, python/gradbench/evals/gmm/run.py, python/gradbench/evals/ht/run.py, python/gradbench/evals/lstm/run.py, python/gradbench/evaluation.py, python/gradbench/pytorch/lstm.py, python/gradbench/tensorflow/ba.py
This adds a new validator, gradbench.evaluation.mismatch, and a function, gradbench.comparison.compare_json_objects, that produces fairly human-friendly descriptions of mismatches between expected and actual results.
All ADBench-derived evals have been modified to use it.
I had to modify the pytorch implementation of lstm, which had a small bug where it returned a singleton list instead of a scalar (this was not detected by the previous validation).
=> Better error messages on validation errors.

crates/gradbench/src/cli.rs
This PR improves the output of `gradbench run`. For example:
```sh
./gradbench run --eval './gradbench eval ht' --tool './gradbench tool pytorch'
```
Before:
```
[   0] Ready.
[   1] Defining module "ht"... success.
[   2] Eval objective                 hand1_t26_c100    11420000 ns (evaluate) ✓
[   4] Eval jacobian                  hand1_t26_c100  2842243293 ns (evaluate) ✓
[   6] Eval objective                 hand2_t26_c192     6060250 ns (evaluate) ✓
[   8] Eval jacobian                  hand2_t26_c192  6466435920 ns (evaluate) ✓
[  10] Eval objective                 hand1_t26_c100    25684750 ns (evaluate) ✓
[  12] Eval jacobian                  hand1_t26_c100  10651882380 ns (evaluate) ✓
[  14] Eval objective                 hand2_t26_c192    13700583 ns (evaluate) ✓
[  16] Eval …
```
=> Make `gradbench run` output nicer

crates/gradbench/src/cli.rs
Following up on https://github.com/gradbench/gradbench/pull/157#issuecomment-2533050965:
> I think the first question most users will ask is "which of the numbers should I look at?"
This PR helps by making the less-precise timing numbers less visually prominent:
=> Use dimmed color for protocol-level timings

python/gradbench/pytorch/ba.py, python/gradbench/pytorch/gmm.py, python/gradbench/pytorch/ht.py, python/gradbench/pytorch/lstm.py, python/gradbench/tensorflow/ba.py, python/gradbench/tensorflow/gmm.py
Importantly, this moves the invocation of the "prepare" method out of the timing loop. Depending on the PyTorch backend, "prepare" might be very costly (e.g. copying data to a GPU), but is unrelated to AD.
A future addition could be to also return timing information for "prepare", in case anyone would find that interesting.
=> Construct the ADBench wrapper objects in prepare_input method.

cpp/adbench/shared/hello.h
This is to ensure that it is usable with operator overloading-based AD tools, which is consistent with the other C++ objective functions.
Of course the 'hello' eval is so trivial that it takes less time to implement than to import, but I think it is useful to use it for demonstrating "best practice".
=> Make objective_hello a template function.

cpp/adbench/io.cpp, cpp/adbench/io.h, cpp/adbench/main.h, tools/enzyme/run.py, tools/finite/run.py, tools/manual/run.py, tools/tapenade/run.py
Rather than extending the ADBench-defined input data structures with a "runs" field, I opted to make the JSON parsing functions (which are custom to GradBench) write to a separate "runs" variable. This was done solely to minimise code differences with ADBench.
=> Support multiple runs in C++-based tools.

tools/enzyme/EnzymeHello.cpp
This reveals a testing weakness: if a bug is introduced that makes 'define' messages fail, CI will not notice.
=> Fix Enzyme, which was quietly broken in #167.

cpp/adbench/main.h
VLAs are not standardised in C++.
=> Replace VLAs with std::vector.

cpp/adbench/shared/lstm.h, tools/adept/AdeptLSTM.cpp, tools/adept/AdeptLSTM.h, tools/finite/FiniteLSTM.cpp, tools/finite/FiniteLSTM.h, tools/manual/ManualLSTM.cpp
This is consistent with the other parameters (and other objective functions for that matter), and is necessary for Enzyme to easily accept the lstm_objective function.
=> Make LSTM accept pointer instead of vector for state.

.github/workflows/nightly.yml, crates/gradbench/src/cli.rs
I want the eval and tool names on the GradBench website to be links to the `README.md` files in this repo. By including the commit SHA in the `summary.json` for each nightly run, we can have those be permalinks which will be guaranteed valid.
=> Include commit SHA in nightly `summary.json`

tools/adept/Dockerfile, tools/adept/Makefile
No user-visible change, but much easier to run outside of Docker, as you no longer have to set bespoke environment variables.
=> Clean up the Adept tool.

cpp/adbench/shared/gmm.h, tools/enzyme/EnzymeGMM.cpp, tools/enzyme/Makefile
This is by adding `__restrict__` to the GMM objective function (significant impact, may also help other tools) and telling the compiler not to worry about errno for math functions (much smaller impact).
Enzyme is still inexplicably slow for GMM.
=> Speed up Enzyme a bit.

.github/workflows/build.yml
See https://github.com/gradbench/gradbench/issues/144#issuecomment-2625171674.
=> Only build slow tools cross-platform on nightly

.github/workflows/build.yml, crates/gradbench/src/cli.rs, gradbench.ps1
This PR tweaks the CLI a bit so it works correctly on Windows, adds a `gradbench.ps1` counterpart to the `gradbench` shell script, and adds a CI check that the latter at least supports the `help` subcommand.
=> Make the CLI work on Windows

crates/gradbench/src/cli.rs, crates/gradbench/src/main.rs
Prerequisite for #219 to hopefully make GitHub recognize it as a rename.
=> Rename `cli::cli` to `cli::main` in `gradbench`

crates/gradbench/src/main.rs
Followup on #226, prerequisite for #178 and #218. This will also allow us to easily add flags to choose which outcomes should produce failure exit codes and which shouldn't; see https://github.com/gradbench/gradbench/pull/178#pullrequestreview-2534497042.
=> Collect intermediary outcomes into an `enum`

Cargo.lock, crates/gradbench-floretta/Cargo.toml, crates/gradbench-floretta/src/main.rs, crates/gradbench/Cargo.toml, crates/gradbench/src/main.rs, python/gradbench/gradbench/eval.py, tools/floretta/Dockerfile, tools/floretta/README.md, tools/floretta/hello.wat, tools/floretta/target.py
This PR has a few little neat things:
1. This initial GradBench implementation for the tool doesn't report any `timings` in response to `evaluate` messages, catching a bug in `python/gradbench/gradbench/eval.py` which I've now fixed.
2. Some of the commands in the Dockerfile need to specify the [Rust target](https://doc.rust-lang.org/rustc/platform-support.html), which depends on [`TARGETARCH`](https://docs.docker.com/reference/dockerfile/#automatic-platform-args-in-the-global-scope); I map between Docker and Rust targets via a small Python script.
3. The Dockerfile uses a [multi-stage build](https://docs.docker.com/build/building/multi-stage/) to produce an image smaller than 20 megabytes, which is one or two orders of magnitude smaller than our other Docker images.
4. Using `cargo run` …
=> Add Floretta tool

.github/workflows/build.yml
#226 and #233 made that job slower; this PR makes it faster by renaming the `lint` job to `test` and putting `cargo test` in there instead, and also only building `--package gradbench` instead of all crates.
=> Speed up `cli` job in CI

.github/workflows/build.yml, crates/gradbench/src/main.rs
This PR should make #227 not matter as much, while also giving us better CI signal on PRs like #224. Now there's just one `run` job which depends on a single `x86-tool` job, and the multi-platform images are built in a single `tool` job that depends on the `run` job to ensure that it runs after it and thus doesn't take up GitHub Actions runners while the `run` job is in progress.
=> Build all multi-platform images in a separate job

nix/shell.nix, tools/enzyme/Dockerfile, tools/enzyme/Makefile
This is useful for people who don't want to run everything inside Docker, but still want some measure of a predictable environment.
Also slightly modifies Enzyme to make it run well both within Docker and Nix.
This shell.nix does not pin Nixpkgs, which is strictly speaking not ideal, but pinning would just add an extra maintenance burden. I'll add pinning if/when I regret not doing so in the first place, or when others also start using this shell.nix.
=> Add Nix setup with shell.nix

README.md
Following up on an oversight from #213.
=> Add `"success"` field to example in `README.md

CONTRIBUTING.md
I guess they must have changed it since #8, which was June last year.
=> Update link for installing QEMU

.github/workflows/nightly.yml, crates/gradbench/src/main.rs
Following up on #247 to make the list of jobs a bit easier to read.
=> List tool before eval in `run` matrix

.vscode/extensions.json
No longer relevant as of #239.
=> Remove Ionide from VS Code extensions

.dockerignore
Before this change, I couldn't build the Futhark Docker image locally; for instance, on commit cc5d4b224d96900eaa25539464637951f975539f:
```
$ ./gradbench repo build-tool futhark
[+] Building 16.9s (15/16)                                                                                                           docker:desktop-linux
=> [internal] load build definition from Dockerfile                                                                                                 0.0s
=> => transferring dockerfile: 789B                                                                                                                 0.0s
=> [internal] load metadata for docker.io/library/python:3.11-slim                                                                                  0.4s
=> …
```
=> Put `tools/futhark/lib` in `.dockerignore`

.github/workflows/build.yml, .github/workflows/nightly.yml
This PR effectively just undoes #84. Currently, `main` CI has a bit of a race condition in the `deploy` job, and it's about to get a much more significant race condition in the `stats` job added by #270. I don't remember exactly what was the behavior when I did #84, but if it was that only the most recent workflow run gets queued up while waiting for the current one, that seems good; the bad scenario would be where _multiple_ workflow runs queue up serially, in which case I'll revisit this.
=> Prevent race condition in CI/CD

.github/workflows/delete-branches.yml
Based off of penrose/penrose#1375, going along with #270. We only really need the _commits_ in those branches; the branch itself is just used when pushing the generated commit.
=> Add workflow to automatically delete CI branches

evals/ba/Dockerfile, evals/gmm/Dockerfile, evals/ht/Dockerfile, evals/kmeans/Dockerfile, evals/lstm/Dockerfile
Following up on #264, these images shouldn't need PyTorch at all anymore.
=> Don't install PyTorch in eval Docker images

evals/ba/Dockerfile, evals/gmm/Dockerfile, evals/ht/Dockerfile, evals/kmeans/Dockerfile, evals/lstm/Dockerfile
This is to ensure we get a fresh build, no matter what we might have copied in from the build host.
=> Pass -Bj when building manual tool in eval Dockerfiles.

.github/workflows/build.yml, .github/workflows/close-pr.yml, .github/workflows/delete-branches.yml, .github/workflows/nightly.yml
According to actions/runner-images#10636, `ubuntu-latest` finished switching over to meaning `ubuntu-24.04` about a month ago, so it seems reasonable to switch.
=> Upgrade GitHub Actions from Ubuntu 22.04 to 24.04

tools/futhark/futhark_utils.py
This should make problems like #286 easier to diagnose.
=> futhark: fail noisily when runtime information is missing

.github/workflows/build.yml, .github/workflows/nightly.yml
Seeing the build fail in #270 after bumping the Ubuntu version in #280 made me think that it'd be nice to build fully a static binary in CI (not that that'd actually have prevented those build failures, of course). Not sure why I didn't do this before.
=> Build CLI for musl

packages/gradbench/src/App.css
Quick followup on #270, making it so we only use [`cursor: pointer`](https://developer.mozilla.org/en-US/docs/Web/CSS/cursor) for row headers that are actually clickable.
=> Don't use `cursor: pointer` for unclickables

Cargo.lock, crates/gradbench-floretta/Cargo.toml, crates/gradbench/Cargo.toml
I made the `**/Cargo.toml` changes, then deleted `Cargo.lock` and ran `cargo test` to regenerate it. I also updated to the Rust 2024 edition because the GitHub Actions `ubuntu-24.04` runners have Rust 1.85.0 as of actions/runner-images#11655.
=> Update Rust dependencies

crates/gradbench-floretta/Cargo.toml, crates/gradbench/Cargo.toml
Not all package systems yet have a compiler with Rust 2024 support (it was released about two weeks ago).
=> Use 2021 edition of Rust

cpp/gradbench/evals/kmeans.hpp
The `__restrict__` annotations significantly help Enzyme. The use of std::min could theoretically help tools based on operator overloading, but I don't have any clear evidence that it does. It does make the code look slightly nicer.
=> Improve kmeans::objective

.github/workflows/build.yml
Resolves #322 by just always trying to push and ignoring errors, instead of attempting to check permissions beforehand, since I don't know how to do that correctly. Also fixes #319.
=> Ignore push errors instead of checking permissions

.github/workflows/build.yml
I added this in #234, but it makes CI significantly slower; usually it takes either about 15 seconds or about 1 minute, which really adds up when there are over a hundred jobs in the matrix. And it seems unnecessary, since nightly doesn't have it and has been working fine.
Plot generated by running these commands...
```sh
gh run view 13619988564 --log > log.txt
uv run collect.py
```
... using this script:
```python
import re
from collections import defaultdict
from datetime import datetime
from pathlib import Path
import matplotlib.pyplot as plt
timestamps = defaultdict(list)
regex = re.compile(r"^(.*)Increase disk space\t(\S*)")
for line in Path("log.txt").read_text().splitlines():
caps = regex.match(line)
if caps:
timestamps[caps.group(1)].append( …
```
=> Don't try to increase disk space in the `run` job

packages/gradbench/src/Stats.tsx
Thanks @lecopivo for noticing this!
---
Before:
---
After:
=> Undo wrong x-axis sorting on website

Cargo.lock, crates/gradbench/Cargo.toml, crates/gradbench/src/main.rs
Addresses the Docker part of #225 by checking for the regex `^#\d+ \d` in the `docker build` output with [`--progress=plain`](https://docs.docker.com/reference/cli/docker/buildx/build/#progress), and printing all output if any such lines are found. For the common case of using `./gradbench repo eval` and `./gradbench repo tool` at the same time, the former is printed in blue and the latter is printed in magenta.
=> Print Docker output when build is not cached

.github/workflows/nightly.yml
I realized we should probably do this while I was working on #341.
=> Only update `nightly` branch if build succeeds

evals/ba/Dockerfile, evals/gmm/Dockerfile, evals/hello/Dockerfile, evals/ht/Dockerfile, evals/kmeans/Dockerfile, evals/lstm/Dockerfile, tools/adept/Dockerfile, tools/adol-c/Dockerfile, tools/cppad/Dockerfile, tools/enzyme/Dockerfile, tools/enzyme/Makefile, tools/finite/Dockerfile, tools/floretta/Dockerfile, tools/futhark/Dockerfile, tools/haskell/Dockerfile, tools/jax/Dockerfile, tools/manual/Dockerfile, tools/ocaml/Dockerfile, tools/pytorch/Dockerfile, tools/scilean/Dockerfile, tools/tapenade/Dockerfile, tools/tensorflow/Dockerfile, tools/zygote/Dockerfile
This works with no downsides and maybe a purist can argue that it more appropriate since the Docker images have no 'gradbench' user. However, the real reason I am proposing this is simply because the Singularity container manager, which is relatively widely used in HPC environments, ends up removing /home/gradbench (under some important circumstances) because it has its own automation logic for handling /home.
=> Change all Docker images to use /gradbench instead of /home/gradbench

crates/gradbench/src/intermediary.rs
Now it's just up to the tool. For example, running this command:
```sh
./gradbench run --eval "./gradbench repo eval kmeans" --tool "./gradbench repo tool codipack"
```
Before:
```
[0] start kmeans (codipack)
[1] def   kmeans                              3.988 s ✓
[2] eval  kmeans::cost    k=10,n=1000,d=8     1.048 s ~         0ms evaluate × 16296,         0ms prepare ✓
[4] eval  kmeans::dir     k=10,n=1000,d=8     1.024 s ~         6ms evaluate × 156,         0ms prepare ✓
[6] eval  kmeans::cost    k=10,n=1000,...     1.042 s ~         0ms evaluate × 8723,         0ms prepare ✓
[8] eval  kmeans::dir     k=10,n=1000,...     1.056 s ~         9ms evaluate × 105,         0ms prepare ✓
[10] eval  kmeans::cost    k=10,n=10000...     1.129 s ~         0ms evaluate × 1563,         0ms prepare ✓ …
```
=> Don't reorder timing names in the intermediary

tools/codipack/run_gmm.cpp, tools/codipack/run_lstm.cpp
Based on a discussion on the Discord, I decided to make the CoDiPack implementations of GMM and LSTM explicitly reset the tape (and indicate the inputs) during each evaluation. This is due to uncertainty about how much work CoDiPack can otherwise reuse across evaluations - the first executions are *much* slower than the rest.
CoDiPack is still pretty fast overall, but this does make it slower on some workloads.
=> codipack: reset the tape before each evaluation

.github/workflows/build.yml, .github/workflows/nightly.yml, Cargo.toml, crates/gradbench/src/intermediary.rs, crates/gradbench/src/main.rs, gradbench
For instance, on commit e72bcebcac3b3eb9a67fe7c66c4479d8881c46bb:
```
$ gh run download 13773302593 --dir run --pattern 'run-*'
$ rm -r run/run-ba-manual
$ ./gradbench repo stats run -o stats
ba
run/run-ba-adept/log.jsonl
run/run-ba-adol-c/log.jsonl
run/run-ba-codipack/log.jsonl
run/run-ba-enzyme/log.jsonl
run/run-ba-finite/log.jsonl
run/run-ba-futhark/log.jsonl
run/run-ba-manual/log.jsonl
No such file or directory (os error 2)
$ RUST_BACKTRACE=1 ./gradbench repo stats run -o stats
ba
run/run-ba-adept/log.jsonl
run/run-ba-adol-c/log.jsonl
run/run-ba-codipack/log.jsonl
run/run-ba-enzyme/log.jsonl
run/run-ba-finite/log.jsonl
run/run-ba-futhark/log.jsonl
run/run-ba-manual/log.jsonl
No such file or directory (os error 2)
```
In contrast, on commit a6a7e31cdae4c47df2e6ae9a6d5a1cb7e9815633:
``` …
```
=> Support backtraces for all CLI errors

crates/gradbench/src/intermediary.rs
Otherwise a misbehaving (crashing) tool can result in a log file that is invalid JSON, which is a very unfortunate situation.
Fixes #278.
=> intermediary: log after we are sure the response is good

.vscode/settings.json
We've been running it in CI since #147, so might as well automatically enable it in VS Code too.
=> Enable Clippy in VS Code

tools/enzyme/Dockerfile
Now builds from a more controllable Debian image, and also ensure that the Enzyme Clang plugin is built (although we don't yet use it).
The main short-term purpose of this is actually to get a slightly newer version of LLVM.
=> Tweak Enzyme Dockerfile

packages/gradbench/src/Stats.tsx
These colors are pretty arbitrarily set, but easy to change. It still doesn't make the graphs exactly easy to read, but at least they are unambiguous. When I could not find a theme color on a tool home page, I tried writing the tools name in 1337 speak.
Fixes #346.
=> Explicit tool colors when plotting

packages/gradbench/src/Stats.tsx
I think it gives a better overall view of which tools are fast and which are slow.
=> Put the derivative chart above the ratio chart

shell.nix
I don't see a reason to list all the Python packages separately via Nix, resulting in different versions from `uv.lock`. @athas I seem to remember you saying there was some reason not to do this, though; can you remind me what that is?
=> Use uv in `shell.nix`

shell.nix
This helps some programs (mostly or exclusively Python libraries in our case) that search LD_LIBRARY_PATH using bespoke bechanisms that the usual Nix automation has not patched.
=> Add all dependencies to LD_LIBRARY_PATH

.github/workflows/build.yml, .prettierignore, .prettierrc.json, .vscode/settings.json, CONTRIBUTING.md, package.json, tools/adol-c/README.md, tools/ocaml/README.md
This PR splits our `test` CI job into three `check-*` jobs according to what tools need to be installed for each, and adds Prettier to the `check-js` job. For consistency and convenience, I also created a [`.prettierignore`](https://prettier.io/docs/ignore) file and added relevant stuff to `CONTRIBUTING.md` and `.vscode/settings.json`.
=> Run Prettier in CI

.github/workflows/build.yml
Meant to do this back in #147 but I didn't know how; turns out it's not hard: https://doc.rust-lang.org/clippy/usage.html#command-line
=> Fail CI if Clippy warns

crates/gradbench/src/intermediary.rs
This kills the tool process when the intermediary fails with a timeout.
Fixes #374, but will in most cases not actually kill all subprocesses spawned by the tool, in case they are in a sub-process group.
=> intermediary: kill tool on timeout

evals/ba/README.md, evals/det/README.md, evals/gmm/README.md, evals/hello/README.md, evals/kmeans/README.md, evals/llsq/README.md, evals/lstm/README.md, evals/ode/README.md, evals/particle/README.md, evals/saddle/README.md, tools/futhark/README.md, tools/haskell/README.md, tools/manual/README.md, tools/ocaml/README.md
The idea behind the Commentary is to have a place for non-normative information about evals and tools. We can imagine the Commentary helps in the following cases:
* You are writing a paper about some new AD tool, and you need to explain why some of the existing implementations in GradBench are particularly slow or fast.
* You want to add a new tool to GradBench, and you are looking for advice on which evals to start with.
=> Add Commentary

crates/gradbench/src/main.rs
Only done on the quiet path. This is critical for Podman-based Dockers, which print diagnostics to stdout. Otherwise, 'gradbench repo tool' will not work, as the diagnostics interfere with the protocol.
=> intermediary: set 'docker build' stdout to /dev/null

tools/scilean/Main.lean, tools/scilean/evals.txt
I can't reproduce the issue with `lstm` in a separate executable. Right now, I have no idea how to debug this. So this PR temporarily disables `lstm` for SciLean
=> Temporarily disable `lstm` benchmark for SciLean

julia/GradBench/src/GradBench.jl, julia/GradBench/src/benchmarks/ba.jl, julia/GradBench/src/benchmarks/gmm.jl, julia/GradBench/src/benchmarks/ht.jl, julia/GradBench/src/benchmarks/lstm.jl, tools/zygote/README.md, tools/zygote/evals.txt, tools/zygote/run.jl, tools/zygote/run_ba.jl, tools/zygote/run_gmm.jl, tools/zygote/run_ht.jl, tools/zygote/run_lstm.jl
Based on ADBench. Unfortunately, `ba` and `ht` are not as easy to port (and I won't try), as they depend on `Zygote.forward`, which seems to not exist in newer versions of Zygote.
=> Implement LSTM, BA, HT with Zygote

.clangd
- protect c from clangd (fix #517)
- add includes for tapenade
- fix regular expressions in .clangd
Fixes #517.
=> Only enforce cpp17 on cpp files

crates/gradbench/src/intermediary.rs, crates/gradbench/src/log.rs, crates/gradbench/src/main.rs, crates/gradbench/src/outputs/trim_basic.jsonl, crates/gradbench/src/outputs/trim_idempotence.jsonl, crates/gradbench/src/outputs/trim_missing_response.jsonl, crates/gradbench/src/protocol.rs, crates/gradbench/src/util.rs
This PR adds a new command to the gradbench CLI that sets the 'input' and 'output' fields of a log file to null. The purpose of this is to trim the often very large log files produced by GradBench, in the interest of saving on storage space and reading time. For example, the log file for gmm-futhark is reduced in size by about 95% after trimming. Most of the remaining space is taken up by timings.
The use of null allows us to distinguish trimmed log files, as presumably this value will never originally occur.
Although the command implementation is pretty short, I have factored it into a separate file 'log.rs', because I envision that we will eventually have a bunch of such log manipulation commands.
I am not a particularly experienced Rust programmer, so I would like feedback on my …
=> cli: add 'log trim' command

cpp/gradbench/evals/llsq.hpp, tools/futhark/Dockerfile, tools/futhark/llsq.fut
This replaces the pow with an accumulator, like in the Floretta implementation. The speedup is pretty dramatic.
The Futhark tool probably fails, as it depends on a compiler version that isn't going to be released until about 30 minutes from now.
=> llsq: strength reduction

tools/tapenade/ht.cpp
This makes it orders of magnitude faster and also use orders of magnitude less memory somehow. The fact that this saves memory probably implies a memory leak in hand_objective_complicated_d().
=> ht-tapenade: actually exploit sparsity

cpp/gradbench/gd.hpp
- this was the likely source of some gnarly bugs (read: I didn't implement rule-of-three) keeping track of tape pointers.
I suspect that, since the argmax function takes f by const-reference, this change should be ok.
=> add cref to function wrapper object in `gd.hpp`

crates/gradbench/src/main.rs, crates/gradbench/src/outputs/dry_run.sh, crates/gradbench/src/outputs/dry_run_output.sh, crates/gradbench/src/outputs/dry_run_timeout.sh
For consistency, and also because it might be necessary for #227. As a nicety, this PR refactors a bunch of our Docker-related functions in `main.rs` into a new `Docker` struct, which cuts down on the lengths of the parameter lists they all used to have.
=> Support `-t`/`--tag` arg on all Docker subcommands

crates/gradbench/src/log.rs, crates/gradbench/src/main.rs, crates/gradbench/src/util.rs
To address the concerns of code duplication from #529, this PR creates an `InOut` trait with a helper function that should make it easy to handle this pattern in the future, e.g. for #533.
=> Refactor input/output polymorphism for `log trim`

python/gradbench/gradbench/tools/tensorflow/ht.py
This is to work around the CI flakiness documented in #390.
If the implementation is ever improved, this bit of sabotage is easy enough to remove.
=> ht-tensorflow: error out on large workloads

.vscode/settings.json, CITATION.cff, CONTRIBUTING.md, README.md
This add a file containing metadata for citing GradBench. It is relevant because I have some students who will need to cite GradBench properly soon-ish. The citation file only covers GradBench as a software artifact, not any papers that we will likely write based on it.
I simply added everyone who has commits in GradBench as an author, ordered by their first commit. This seems the most fair. It cannot be fully automated, because people will eventually make commits using different names, email addresses, or anonymously. However, I don't expect maintenance of this file to be particularly onerous. It is also not a permanent record, so we can add ORCIDs and such over time.
If this is accepted, a good next step is to also upload GradBench to [Zenodo](https://zenodo.org/). There are GitHub …
=> Add CITATION.cff

cpp/gradbench/evals/lse.hpp, evals/lse/README.md
No idea how I forgot to do that, especially since I even documented the resulting bad performance.
=> lse.hpp: also parallelise second loop

crates/gradbench/src/lint.rs
Previously Clippy was ignoring `#[cfg(test)]` code.
=> Pass `--all-targets` to Clippy

.github/workflows/build.yml, .github/workflows/nightly.yml, .gitignore, crates/gradbench/src/log.rs, crates/gradbench/src/main.rs, crates/gradbench/src/outputs/dry_run_download_github.sh, crates/gradbench/src/stats.rs, crates/gradbench/src/util.rs
Resolves #365, resolves #577.
This PR adds flags `--download-github` and `--check` to the `repo run` subcommand so that we can use it in CI to run multiple pairs in a single job, and modifies the `matrix` and `stats` jobs to accommodate this change.
=> Allow multiple eval/tool pairs in a single CI job

CONTRIBUTING.md, crates/gradbench/src/inputs/eval/contributing_md_example.jsonl, crates/gradbench/src/inputs/eval/define_error.jsonl, crates/gradbench/src/inputs/eval/define_success_error.jsonl, crates/gradbench/src/inputs/eval/define_timings.jsonl, crates/gradbench/src/inputs/eval/evaluate.jsonl, crates/gradbench/src/inputs/eval/evaluate_null_output.jsonl, crates/gradbench/src/inputs/eval/intermediary_timeout.jsonl, crates/gradbench/src/inputs/eval/start_names.jsonl, crates/gradbench/src/inputs/tool/contributing_md_example.jsonl, crates/gradbench/src/inputs/tool/define_error.jsonl, crates/gradbench/src/inputs/tool/define_success_error.jsonl, crates/gradbench/src/inputs/tool/define_timings.jsonl, crates/gradbench/src/inputs/tool/evaluate_error.jsonl, crates/gradbench/src/inputs/tool/evaluate_failure_no_error.jsonl, crates/gradbench/src/inputs/tool/evaluate_null_output.jsonl, crates/gradbench/src/inputs/tool/evaluate_success_error.jsonl, crates/gradbench/src/inputs/tool/evaluate_success_no_output.jsonl, crates/gradbench/src/inputs/tool/intermediary_timeout.jsonl, crates/gradbench/src/inputs/tool/start_names.jsonl, crates/gradbench/src/intermediary.rs, crates/gradbench/src/outputs/contributing_md_example.txt
This PR greatly reduces the amount of code needed to write the tests for the intermediary.
=> Write intermediary test inputs as `*.jsonl`

python/gradbench/gradbench/eval.py
This fixes a bug leftover from #213, in which evals would simply not run the validator at all if the tool returned `"output": null`. I ran into this while working on #568, since I set the TensorFlow `jacobian` function to just `return None` while I was working on the `objective`, and I was surprised to see that that caused everything to just pass.
=> Don't skip validation for `"output": null`

tools/ocaml/Dockerfile
I am somewhat disturbed that opam seems to remove package versions sometimes.
Fixes #631.
=> ocaml: bump dune

.github/workflows/build.yml
This is an alternative to #635 for fixing the CI lint job.
One "advantage" is that now `shell.nix` actually gets tested in CI. The main disadvantage is that now the lint job takes longer: it's about ten minutes instead of two. But it seems like we could potentially eliminate this using caching: https://github.com/cachix/cachix-action
Another disadvantage is that the commands in the lint job now have to use `nix-shell --command` which is annoying; I wonder if there's a way to just automatically do that for all shell commands in a CI job.
=> Use Nix for CI lint job
